Mobile menu
altontonn/portfolio pull request #10
Opened 2022-06-14 12:43 UTC by altontonn

Add menu bar to display the menu on mobile screen

2022-06-14 13:22 UTC, tufoinnkuo10 requested changes
Hi @altontonn 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ Documented your work professionally
✅ Mobile menu hamburger looks good

Required Changes ♻️
Check the comments under the review
-[required] Please use the correct linters check. you can check them [here](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [required ] your mobile popup menu after clicking the hamburger icon does not work. please fix that. the next reviewer will check it when it starts working. great job 😄 

Optional suggestions
- [optional] please always ensure that your code works before submitting it for a review
- [ optional] please kindly make your mobile and desktop app responsive. there are some breaks when switching between them.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-14 13:22 UTC, tufoinnkuo10 commented on index.html
>                          <div class="bar-b"><a href=""></a></div>
- [ ] please your navigation bar should have the same color as the Figma version.
your nav
![Screenshot (115)](https://user-images.githubusercontent.com/65298048/173585688-f036d9f8-79fd-4a68-aca7-d892dcb2ec0c.png)
figma version
![Screenshot (114)](https://user-images.githubusercontent.com/65298048/173585793-abdca7fb-8fa3-477f-9458-f75b2a5236ed.png)

2022-06-14 13:22 UTC, tufoinnkuo10 commented on index.html
>                      </div>
- [ ] please make the hamburger active so when a user clicks a menu appears with links to the various sections and a close icon. 👇🏾
![Screenshot (116)](https://user-images.githubusercontent.com/65298048/173586190-1c72f053-eab5-4cd6-964d-06fa90e48c1c.png)

2022-06-14 13:22 UTC, tufoinnkuo10 commented on index.html
>                          <div class="bar2"><a href="">About</a></div>
- [ ] kindly add links to the different menu sections

2022-06-15 11:59 UTC, keroloussamy requested changes
Hi @altontonn, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 11:59 UTC, keroloussamy commented on index.html
> +                </label>
- [ ] Kindly make the hamburger button match the Original design.
- [ ] Kindly there's a horizontal scrolling on your page kindly fix it to match the original design.

Your design
![image](https://user-images.githubusercontent.com/35535130/173821333-c7882272-6e16-4c6c-a5f6-46405f8b6e41.png)

Original design
![image](https://user-images.githubusercontent.com/35535130/173821627-73ce736a-4a0a-4131-b3f1-dd65615b893b.png)

2022-06-15 11:59 UTC, keroloussamy commented on index.html
> +                            <a href="">Contact</a>
- [ ] Kindly as asked by the previous reviewer, add links to your menu options.
Like `<a href="#contact">Contact</a>` `#contact` here is the name of the id for this section in your page.

2022-06-15 12:56 UTC, vechicin requested changes
# Hi @altontonn ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing some of the changes required by the previous reviewers

 ## Required Changes ♻️

- [ ] I apologize about previous reviewers not mentioning this, but you should've set up JavaScript linters as well.

<img width="778" alt="Screen Shot 2022-06-15 at 7 54 24" src="https://user-images.githubusercontent.com/82426682/173831844-1cb7b60b-363a-4f5c-8753-902c516c6af8.png">

Please refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/html-css-js) and follow the README instructions to set up Eslint correctly.

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 12:56 UTC, vechicin commented on main.css
> +  }
Your menu still doesn't look quite like the one from the template design.

Your design:

<img width="188" alt="Screen Shot 2022-06-15 at 7 44 09" src="https://user-images.githubusercontent.com/82426682/173829816-15b7188e-a807-4bca-998f-f2a9fabac032.png">

The template design:

<img width="323" alt="Screen Shot 2022-06-15 at 7 45 04" src="https://user-images.githubusercontent.com/82426682/173830022-73076066-d0e9-4e55-b2df-1e0a2899d1b9.png">

Some (but not all) of the things you should fix are the font, colors, margins, padding, and dividers. Additionally, make sure the menu covers the entirety of the screen horizontally AND vertically, it makes for bad UI/UX to be able to see portions of the page like in the screenshot above.

Additionally, the close icon should be visible at all times. However, it is not, that is because the menu is not fixed but it is scrolling with the page. That shouldn't happen, please fix it.

2022-06-15 12:56 UTC, vechicin commented on js/main.js
> +let bar = document.querySelector(".navigation__checkbox");
When clicking the links on the menu, not only should I be taken to the correct section of the page, the menu itself should close automatically.

<img width="587" alt="Screen Shot 2022-06-15 at 7 49 46" src="https://user-images.githubusercontent.com/82426682/173830916-5eeeca98-ee14-4679-8696-d9944eefbd32.png">

Kindly fix this.

2022-06-15 13:03 UTC, altontonn commented on js/main.js
> +let bar = document.querySelector(".navigation__checkbox");
Should I remove CSS linters

2022-06-15 13:16 UTC, altontonn commented on js/main.js
> +let bar = document.querySelector(".navigation__checkbox");
Hey, what should I do coz js linters have similar file name as js, should I rename js diles them

2022-06-15 16:15 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @altontonn, and @Fadahunsiseyi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
- [ ] As requested by the previous reviewer, Please make sure to set up linter for HTML, CSS, and JavaScript. Check this [repo](https://github.com/microverseinc/linters-config/tree/master/html-css-js) for how to set up linter.
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 16:15 UTC, thecodechaser commented on index.html
>                      </div>
- [ ] As requested by the previous reviewer, Please make sure that your design matches the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) design.
  - Please increase the font size and use the correct color for mobile menu options. `#FFF5E1`
  - Please decrease the size of close(X) button.

### Your design

![image](https://user-images.githubusercontent.com/83803414/173873819-5613b2b8-3a38-493b-9c8d-f8fd03be55df.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/173873875-dcdc589c-c8db-45b8-9232-47a1d388d0ba.png)

2022-06-15 16:15 UTC, thecodechaser commented on js/main.js
> +  bar.addEventListener('click', function(){
- [ ] After opening the mobile menu and closing it, I can not open the mobile menu until I refresh the page. Please make sure to fix this issue.

2022-06-18 20:12 UTC, merged