Popup
altontonn/portfolio pull request #11
Opened 2022-06-17 13:56 UTC by altontonn

### JavaScript Objects

- create an image pop for my portfolio see project button
- used JavaScript objects to store project portfolio name, image, description

2022-06-17 15:42 UTC, ishimwezachee requested changes
Hi @altontonn and @alanluqman   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-06-17 15:42 UTC, ishimwezachee commented on js/main.js
> +
- [ ]  Your Array  should contain all data that correspond to number of the cards you have in you website. Please add more data and implement the logic that will display those data depending on the` see project` button you clicked too.

2022-06-17 15:42 UTC, ishimwezachee commented on js/main.js
> +  <div class="img-text">
- [ ]  You should loop the data so that you data are dynamic and displayed with the right content based on the button you've clicked too.

2022-06-17 15:42 UTC, ishimwezachee commented on index.html
>              </div>
- [ ]  You should have a design similar to the one from the design, please make sure that you followed the provided design from Figma. 


Your design | Figma design
--- | ---
![image](https://user-images.githubusercontent.com/43877689/174329897-3379496c-2ed4-4d56-b9bf-7d1e7841503e.png) | ![image](https://user-images.githubusercontent.com/43877689/174330615-60d8dd24-726e-4c4b-a0ce-d6d03e04beee.png)

2022-06-18 00:35 UTC, omarsalem7 requested changes
Hi @altontonn, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 00:35 UTC, omarsalem7 commented on index.html
>              </div>
- [ ] As mentioned by previous reviewer please try to match your design with Figma template and also when you make changes in mobile version, I can't see close (X) button for model.

> 
| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/174415025-1628a8f0-2df4-48f1-9ebe-edefe57834f2.png) | ![image](https://user-images.githubusercontent.com/43877689/174330615-60d8dd24-726e-4c4b-a0ce-d6d03e04beee.png) |

2022-06-18 00:35 UTC, omarsalem7 commented on js/main.js
> +  <div class="img-text">
- [ ] As mentioned by previous reviewer, you should create your model in a dynamic way not static when you click in see project, you should see the same data in model like the clicked project not static.
> You can watch this [loom video](https://www.loom.com/share/40fe6aea845847a1a9cc7d92ba055bbc) for more explanation for the requested changes

2022-06-18 02:07 UTC, omarsalem7 requested changes
Hi @altontonn, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 02:07 UTC, omarsalem7 commented on js/main.js
> +  <div class="img-text">
- [ ] Kindly address this issue, you can look the attached loom video for explanation.

> * [ ]  As mentioned by previous reviewer, you should create your model in a dynamic way not static when you click in see project, you should see the same data in model like the clicked project not static.
> 
> > You can watch this [loom video](https://www.loom.com/share/40fe6aea845847a1a9cc7d92ba055bbc) for more explanation for the requested changes

2022-06-18 20:12 UTC, merged