create work section and about me section
altontonn/portfolio pull request #2
Opened 2022-06-30 19:46 UTC by altontonn

### Portfolio and About me

1. Created mobile portfolio and About section with: 

- FLEX
- GRID

2022-06-30 22:35 UTC, vickymarz requested changes
Hi @altontonn , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._

- [ ] I see that you wrapped most of the containers for the technologies categories in a `div` tag. I think you should consider treating the list of technologies as list items by wrapping them in the `ul `tag with each technology wrapped in `li` tag. Doing this will make your code semantic and clean 😄 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:35 UTC, victorokoroji commented on index.html
> +                <h1>Multi-Post Stories </h1>
[OPTIONAL] - Good job wrapping the project title in the `header` tag 👍 . I think you should consider wrapping the project title in other` header `tags like the `h2` tag instead of the `h1` tag as it is recommended to have only one h1 ` tag in your project. This is necessary to make your project more semantic and accessible to web browsers 😎

2022-06-30 22:35 UTC, victorokoroji commented on index.html
> +                    </div>
- [ ] I think you should consider treating the list of technologies as list items by wrapping them in the `ul `tag with each technology wrapped in `li` tag. Doing this will make your code semantic and clean 😄

2022-06-30 22:35 UTC, vickymarz commented on index.html
> +    <section class="works" id="portfolio">
- [ ] Good work you have done on your styling 👍 . I can see that there is so much margin-top and bottom for this section. I think you should consider adjusting the margins for this section to match the margin in the [Figma design template.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) 

| Figma Design | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/176786310-39f0dfe3-9b78-4c4c-ab37-a34ad3de6cbf.png)  | ![image](https://user-images.githubusercontent.com/63473584/176786400-f75d7a6e-b27a-489e-9b07-a6c03bb50580.png)  |

2022-06-30 22:35 UTC, vickymarz commented on index.html
> +                    <button type="button" class="link" id="myBtn">See Project</button>
- [ ] I think you should consider styling the buttons to match the one in the [Figma design template.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) 
. Kindly pay attention to the font color, background, and border 

| Figma Design | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/176787099-d51e8ad5-b6c4-4ac1-be6d-69bba80680df.png)  |  ![image](https://user-images.githubusercontent.com/63473584/176787165-1160c01e-6301-47c9-8bf9-a794a77d6583.png)  |

2022-06-30 22:35 UTC, vickymarz commented on index.html
> +    <section class="about-me" id="about">
- [ ] Good work you have done on your styling 👍 . I can see that there is so much margin-top specified for this section. I think you should consider adjusting the margins for this section to match the margin in the [Figma design template.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) 

| Figma Design | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/176787830-948886ad-8359-4d32-b6dc-f5e08f2e22de.png)  | ![image](https://user-images.githubusercontent.com/63473584/176787882-35c1117d-d629-4b55-81c4-c70429b98606.png)  |

2022-07-01 10:05 UTC, zhadier approved these changes
## Hi @altontonn  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media1.giphy.com/media/d31w24psGYeekCZy/giphy.gif"/>

# Congratulations! 🎉 

### Keep Rocking!👏👏👏
## Optional
<hr/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 10:06 UTC, merged