Feature 2
altontonn/portfolio pull request #3
Opened 2022-05-27 15:18 UTC by altontonn

This is the second part of template 2 in my works section. styles with CSS, FLEXBOX & GRID layout.

2022-05-27 16:08 UTC, zieeco requested changes
Hi @altontonn 


Great work on the work section 👏 
You've done well implementing it, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 16:08 UTC, zieeco commented on index.html
> +        </div>
**[REQUIRED CHANGES]**

- [ ] Hey great job here, but this first card should be in a container aligned using flexbox and the remaining content should be inside of the container that way it will make it easy for your when working on the desktop version using media queries. Please kindly fix this issue

2022-05-27 16:08 UTC, zieeco commented on index.html
> +            </div>
**[REQUIRED CHANGES]**

- To enforce the use of HTML5 semantic tag, kindly use a  `<ul>` tag here as the `<ul>` tag defines an unordered list used together with the  `<li>` tag. you could do this to achieve that:
```

<ul>
  <li>html</li>
</ul>
```
- You could also remove the `a`  tag wrapper as this is not meant to be a link but just a list of technologies.


:point_right: ***NOTE: This change applies to all your cards in the work section. I don't want to duplicate them all over.***

2022-05-27 16:08 UTC, zieeco commented on index.html
> +            <a href="" class="button2">See Project</a>
**[REQUIRED CHANGES]**

- Please kindly add the CSS pseudo-classes to this `<button> or <a>` tag to indicate when it's clicked, hovered, enabled, and disabled to improve the user experience below: 

![click](https://user-images.githubusercontent.com/59397159/170734296-9d51106d-4823-423a-9407-68d015e06905.png)

2022-05-27 17:03 UTC, altontonn commented on index.html
> +        </div>
Do you mean all the div to be in a container or each div?

2022-05-27 23:10 UTC, Kandy-Peter requested changes
Hi @altontonn    

Good job so far!
You did a great job of implementing some changes requested by the previous reviewer. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- Good commit history :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-27 23:10 UTC, Kandy-Peter commented on index.html
> +            <a href="" class="button2">See Project</a>
- [ ] As requested by the previous reviewer, you should implement the button on `:hover`, `:active` and `:disabled`  CSS effects. Kindly, add them to match more the design.
_**You can refer to the design below:**_

![image](https://user-images.githubusercontent.com/80612925/170798854-3a46d4ff-7bb1-41d4-89ec-b1102b3ef56b.png)

2022-05-28 00:41 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @altontonn,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-28 00:43 UTC, merged